apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: infra
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
data:
  JWT_SECRET: ck85akFwQVpmQ0FxM000VFhiSmFSd0dVQ2NJdnJSOWFjM0c4bll2MGVncTRkaDYyM29qd2EwcEVsR3FPZjB0eGJUTHo2dFc3bHBMN0pORXdMWXBrRnY=