apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-user-config
  namespace: infra
data:
  POSTGRES_DB: "userservice"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-auth-config
  namespace: infra
data:
  POSTGRES_DB: "authservice"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-order-config
  namespace: infra
data:
  POSTGRES_DB: "orderservice"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: infra
data:
  MONGO_INITDB_DATABASE: "paymentservice"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: infra
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka.infra.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"